### ISSUE TITLE
use verb mostly broken

### ISSUE THREAD

**Issue by Saturn-99** [UMDLARS/one_night_in_sf#143]
use verb often results in an error. Testers very very often ran into this issue.

**Comment by pahp** [comment]
This makes sense. @Saturn-99 do you think that it's a matter of individual edge cases, e.g., things that people want to say "use X" but it doesn't work (and which we would perhaps need to fix individually), or do you think it's more an issue of how "use" works in general that we would need to fix more universally?

**Comment by Saturn-99** [comment]
```
> use key on door
 
[** Programming error: nothing (object number 0)  has no property instructions to read **]
Many of the objects in this game are useful tools. While 
[** Programming error: tried to test "has" or "hasnt" of nothing **]
the nothing is worth looking at, you won't need to do anything with it.
```

**Comment by Saturn-99** [comment]
This seems to be an issue beyond just the use verb
![image](https://github.com/UMDLARS/one_night_in_sf/assets/116676184/1d750910-bd83-4708-b084-76f3cd61fcc1)

**Comment by spacehobo** [comment]
```
> use key on door
 
[** Programming error: nothing (object number 0)  has no property instructions to read **]
```

This example seems as though the parsing has failed, and instead of `noun` referring to the `key`, it's still a null, pointing at the `nothing` object (number 0, as it says).  I have some suspicions of what could be causing both of these failures, and I'll take a stab at adding some more defensive programming to catch the situation I have in mind, but a proper regression test would be important to have here.
