### ISSUE TITLE
TWN (Three-Word Names)

### ISSUE THREAD

**Issue by pahp** [UMDLARS/one_night_in_sf#243]
A student wrote:

> Maybe the parser doesn't like three word names? It didn't recognize Phillips head screwdriver but did recognize phillips screwdriver, same with loose floor tile vs floor tile.

Can the parser handle TWNs, @spacehobo ? Fix, report, or WONTFIX this as you see fit.

**Comment by libraun** [comment]
Here's some stuff that might help with this:

https://github.com/johanberntsson/PunyInform/wiki/manual#chooseobjectsfinal

https://github.com/johanberntsson/PunyInform/wiki/manual#parser

**Comment by spacehobo** [comment]
Names are meant to be entered as a list of dictionary words.  One example from page 57 of [the DM4](http://inform-fiction.org/manual/DM4.pdf) is:

```
Object magpie "black-striped bird"
  with name ’magpie’ ’bird’ ’black-striped’ ’black’ ’striped’,
    wingspan 5, worms_eaten;
```

Note that instead of trying to use a *string* such as "black-striped bird" (which is the display name declared), they listed each component descriptive word in the `name` array.  Using a string (double-quotes) won't work: the `name` array only accepts single dictionary words.
